# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('has_faceset', models.BooleanField(default=False)),
                ('modify_time', models.DateTimeField()),
            ],
        ),
    ]
