# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceunlock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_md5',
        ),
    ]
